### ISSUE TITLE
Current package-lock.json causes npm install to fail

### ISSUE THREAD

**Issue by rkben** [IBM/hello-carbon-vue3#1]
Workaround: `rm package-lock.json`

Perhaps some carbon dep using a local repo at some point?
```
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to http://localhost:4873/@carbon/icons-vue/-/icons-vue-10.65.1.tgz failed, reason: connect ECONNREFUSED ::1:4873
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/node_modules_18/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:502:9)
npm ERR!     at Socket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!  FetchError: request to http://localhost:4873/@carbon/icons-vue/-/icons-vue-10.65.1.tgz failed, reason: connect ECONNREFUSED ::1:4873
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/node_modules_18/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:502:9)
npm ERR!     at Socket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '::1',
npm ERR!   port: 4873,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rkb/.npm/_logs/2023-03-11T15_32_00_289Z-debug-0.log
```

**Comment by davidnixon** [comment]
First, nice profile pic! I was a little frightened when I opened this issue though. 😄 

Is this from running `npm install` ?
I'll try and reproduce this.

**Comment by rkben** [comment]
Yes from `npm install`

**Comment by rkben** [comment]
4 occurances of localhost being used in `package-lock.json`
https://github.com/IBM/hello-carbon-vue3/blob/main/package-lock.json#L322

**Comment by davidnixon** [comment]
@rkben can you try pulling again. I think I have it fixed.

**Comment by rkben** [comment]
> @rkben can you try pulling again. I think I have it fixed.

It is indeed fixed!
